---
- name: Restart nfs-server
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted
    enabled: yes

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart httpd
  ansible.builtin.systemd:
    name: httpd
    state: restarted
    enabled: yes